apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nvidia
  namespace: flux-system
spec:
  interval: 1m
  path: "./cluster-config/apps/gpu-operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: sd15-api
#   namespace: flux-system
# spec:
#   interval: 1m
#   path: "./cluster-config/apps/sd15-api"
#   prune: true
#   dependsOn:
#     - name: nvidia
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: llm
  namespace: flux-system
spec:
  interval: 1m
  path: "./cluster-config/apps/llm"
  prune: true
  dependsOn:
    - name: nvidia
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
